name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    env:
      NODE_OPTIONS: '--max_old_space_size=4096'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pyinstaller requests PyQt6

    - name: Build executable
      run: |
        pyinstaller --name OpenAI_TTS_GUI --onefile --windowed --icon=logo.ico main.py

    - name: Archive build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: OpenAI_TTS_GUI-${{ matrix.os }}
        path: dist/OpenAI_TTS_GUI*
